### ISSUE TITLE
Let users customize how to access a value in the Distinct operation.

### ISSUE THREAD

**Issue by drupol** [loophp/collection#110]
The user should be able to use the `distinct` operation with a collection of object.

Currently, we use `===` in the Distinct operation to compare values, however, it happens sometimes that we want to customize
how to access to the values to compare.

Code example

<details>

```php
<?php

/**
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

declare(strict_types=1);

namespace App;

use loophp\collection\Collection;

include __DIR__ . '/vendor/autoload.php';

class User {
    private string $name;

    public function __construct(string $name)
    {
        $this->name = $name;
    }

    public function name(): string
    {
        return $this->name;
    }
};

$users = [
    new User('a'),
    new User('b'),
    new User('a'),
    new User('c'),
];

$collection = Collection::fromIterable($users)
    ->distinct();

print_r($collection->all());
```

</details>  

In this particular case, all the users will be returned and the Distinct function will not work.

## How to fix?

The idea is to let users customize how values should be accessed and/or compared.

### Proposal 1

Let users customize how to access to the value to compare.

```php
$collection = Collection::fromIterable($users)
    ->distinct(static fn(User $user): string => $user->name());
```

### Proposal 2

Let users customize how to access to the value to compare and how to compare them.

```php
$collection = Collection::fromIterable($users)
    ->distinct(static fn(User $left, User $right): bool => $left->name() === $right->name());
```

### Proposal 3

Mix the two previous proposals:

```php
$collection = Collection::fromIterable($users)
    ->distinct(
        static fn(User $user): string => $user->name(),
        static fn(string $left, string $right): bool => $left === $right
    ),
```

I tested both proposals and I'm unable to decide which way to go.

Therefore, this issue is to decide on which way to go.

**Comment by AlexandruGG** [comment]
This is a good idea, **Proposal 2** sounds the best to me because there might be more than a single element with objects which will determine equality.

For example, with the `Money` object from moneyphp, you need to compare both the _amount_ and the _currency_. It already has an equals method: https://github.com/moneyphp/money/blob/master/src/Money.php#L112-L126.

In addition, PHPUnit also promotes object comparisons via user-defined `equals` methods, which will be used with this assertion: https://phpunit.readthedocs.io/en/9.5/assertions.html#assertobjectequals. So users might already have this method on my of their value objects.

Proposal 2 allows for both these usages:

```PHP
Collection::fromIterable($users)
    ->distinct(static fn(User $left, User $right): bool => $left->equals($right));

Collection::fromIterable($users)
    ->distinct(static fn(User $left, User $right): bool => $left->name() === $right->name && $left->email() === $right->email());

**Comment by drupol** [comment]
Okay, that was my preference as well.

I added a third proposal, which might be an option as well, do you think it would be better?

**Comment by drupol** [comment]
I implemented the proposal 3 locally so far, I like it. It's fully customizable and the logic is properly decoupled.

WDYT?

**Comment by AlexandruGG** [comment]
I like the third approach, best of both!
