### ISSUE TITLE
suggestion: improve readme by adding short Usage section

### ISSUE THREAD

**Issue by dwenaus** [loophp/collection#17]
It took me a while to finally find this https://loophp-collection.readthedocs.io/en/latest/pages/usage.html
I suggest maybe putting a portion of those usage examples in the readme to increase adoption of this library.

**Comment by drupol** [comment]
Hi,

Writing a better documentation is something to do indeed.

As I wrote in my blog post here: https://not-a-number.io/2020/lazy-collection-oddities/ (in the bottom end), it must have better examples and I'm perfectly aware of it.

That said, finding good real-life use case is a very hard task for me, a little help would be welcome on this.

I'll keep this issue open for now as a reference.

**Comment by drupol** [comment]
Dear @dwenaus ,

The README file has been changed and examples updated. Is it better?
