### ISSUE TITLE
group function accurate?

### ISSUE THREAD

**Issue by duclet** [loophp/collection#19]
## Steps required to reproduce the problem

1. Sample array: `[['id' => 1, 'name' => 'A'], ['id' => 2, 'name' => 'B'], ['id' => 1, 'name' => 'C']]`
2. Doing `Collection::with(arr)->groupBy(function($k, $v) { return $v['id']; })->all()`

## Expected Result
`[
    1 => [
        ['id' => 1, 'name' => 'A'],
        ['id' => 1, 'name' => 'C']
    ],
    2 => [
        ['id' => 2, 'name' => 'B']
    ]
]`

## Actual Result

* `[
    1 => [
        ['id' => 1, 'name' => 'A', [ 0 => ['id' => 1, 'name' => 'C'] ]
    ],
    2 => [
        ['id' => 2, 'name' => 'B']
    ]
]`

Maybe my understanding of what the group function is supposed to do is incorrect by I was thinking it is more in line with what I expect the result to be. The problem seems to be that first time value is set, it is set as is. Second time, it is converted to array and then appended which cause the behavior above. So that means right now, the above would only work for simple values and not arrays or objects.

**Comment by drupol** [comment]
Dear @duclet ,

Thanks for the bug report.

I just submitted a PR that update the behavior of the Group operation.

Do you mind having a look at it and maybe try it to see if it fits now ?

**Comment by drupol** [comment]
PR has been merged closing the issue.
