### ISSUE TITLE
Append functionality.

### ISSUE THREAD

**Issue by benelori** [loophp/collection#22]
I might not be using this accurately, but here's the issue I encountered.

## Steps required to reproduce the problem

I am attempting to use the append method.

1. 
```
$collection = Collection::with(['A', 'B', 'C', 'D', 'E']);
```
2. 
```
$this->collection = $collection
            ->append('F', 'G', 'H')
            ->all(); // ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
```
3. 
```
 public function getCollection()
    {
        return $this->collection;
    }
```

## Expected Result

* getCollection should return ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']

## Actual Result

* ['F', 'G', 'H', 'D', 'E']

Attached repository for reproduction.

https://github.com/benelori/collections

**Comment by drupol** [comment]
Try to add the `normalize` operation after `append`.

**Comment by benelori** [comment]
I can confirm that it's working and I created a PR with the update, unless this is the way it's supposed to work. I haven't dug into the code much, yet. But it seems a bit verbose for a simple append operation.

**Comment by drupol** [comment]
> I can confirm that it's working and I created a PR with the update, unless this is the way it's supposed to work. I haven't dug into the code much, yet. But it seems a bit verbose for a simple append operation.

Thanks, it's committed already.

Feel free to suggest something less verbose anytime soon, I'm curious to see what you have in mind.

**Comment by benelori** [comment]
Sure thing. Less verbose would be like the original documentation i.e. without the ```normalize()```. I will take a look at some point, when I have some time to dig into the code. Thanks for the quick response!

**Comment by drupol** [comment]
> Sure thing. Less verbose would be like the original documentation i.e. without the `normalize()`. I will take a look at some point, when I have some time to dig into the code. Thanks for the quick response!

Ooh that way ok, I understand.

If we want to make it less verbose, then we will need to update the [Append](https://github.com/loophp/collection/blob/master/src/Operation/Append.php) operation and make it more complex.

The goal of this library is to handle key and values. If one day we decide to get rid of keys handling, then I would automatically normalize the result by default.

However, the way this library is not to try to never convert things into an array but merely like that:

```php
<?php

$collection = Collection::with(['A', 'B', 'C', 'D', 'E'])->append('F', 'G', 'H');

foreach ($collection as $key => $value) {
 // do something
}
```

That loop will iterate as such:

* Key: 0 Value: 'A'
* Key: 1 Value: 'B'
* Key: 2 Value: 'C'
* Key: 3 Value: 'D'
* Key: 4 Value: 'E'
* Key: 0 Value: 'F'
* Key: 1 Value: 'G'
* Key: 2 Value: 'H'

Anyway, I think such things should be better documented and your PR was very welcome :-) Keep them coming up !
