### ISSUE TITLE
Issue with cache and fromCallable

### ISSUE THREAD

**Issue by ktrzos** [loophp/collection#264]
Hey 👋. I have this code:

```php
$test = Collection::fromCallable(static function () {
    yield 100 => 'a';
    yield 200 => 'b';
    yield 300 => 'c';
    yield 400 => 'd';
})->cache();

$result1 = $test->get(100)->current();
$result2 = $test->get(200)->current();
$result3 = $test->get(300)->current();
$result4 = $test->get(400)->current();
```

With each run, the result is:

![image](https://user-images.githubusercontent.com/14212721/189178364-c5e29448-3162-4789-95b0-e1a784950069.png)

Using the latest loophp/collection (6.0.3) and PHP 8.1. Is it a bug, or am I doing something wrong 😉?

**Comment by drupol** [comment]
Hi !

Interesting, let me check this out locally with version 6, `master` and I'll get back to you.

**Comment by ktrzos** [comment]
Thank you for VERY fast response @drupol 🍻

**Comment by drupol** [comment]
You're welcome.

I cannot reproduce the issue with the `master` branch, everything seems to be ok there.

Going to investigate the issue on version `^6`...

**Comment by drupol** [comment]
This is the commit who fixed the issue a69acec

**Comment by ktrzos** [comment]
Thanks! I suppose it will be soon pushed on the next library version?

**Comment by drupol** [comment]
I'm still investigating which lines fixed the issue. I need to provide a fix and release a version 6.0.4 with the fix only.

**Comment by ktrzos** [comment]
Ok, no worries. I will wait for it then 🙂. Good luck 🤞!

**Comment by drupol** [comment]
Ok, got the reason.

That commit is actually one of the most important commit. This is mostly the reason why there will be a major version bump.

The sad news is that I'm afraid this won't be fixable in v6 :( it would require to rewrite almost every operations.

The good news is that now I need to hurry and release version 7. I took a bit of delay to finish it. There's still #256 to finish and we're good to go.

**Comment by ktrzos** [comment]
I see. It is ok. I managed to make a workaround on my side by casting the collection to an array (unfortunately), and getting the value by a key at that point. Keep up the good work, and can't wait for v7 🙂.

**Comment by ktrzos** [comment]
And, of course, thank you for your help and fast reaction once again 👍️.

**Comment by drupol** [comment]
I just added your tests in the codebase to make sure it doesn't happen again in v7 :)

Thanks for reporting it !

**Comment by rela589n** [comment]
Hi there!

Does the cache really work in this case?

```
$test = Collection::fromCallable(static function () {
    var_dump('data call');

    yield 100 => 'a';
})->cache();

$result1 = $test->all();
$result2 = $test->all();

var_dump($result1, $result2);
```

This code outputs following result:

```
string(9) "data call"
string(9) "data call"
array(1) {
  [0]=>
  string(1) "a"
}
array(1) {
  [0]=>
  string(1) "a"
}

```

It doesn't seem to work correctly, since it calls for data every time :thinking:

**Comment by drupol** [comment]
This is weird indeed, but this is an expected behavior due to the immutable nature of the Collection.

To make it work "as expected", add the `squash` operation.

However, this issue gaves me an idea to add a new operation `memorize` that would do that... I just did in 5 minutes, I might probably finalize it next week.
