### ISSUE TITLE
[Question] Rename Collection interface to CollectionInterface

### ISSUE THREAD

**Issue by ktrzos** [loophp/collection#273]
When using both an implementation and an interface of collections, there's a need for making an alias:

```php
<?php declare(strict_types=1);

namespace App;

use loophp\collection\Collection;
use loophp\collection\Contract\Collection as CollectionInterface;

final class MyClass
{
}
```

Would it be possible to change the `Collection` **interface** onto `CollectionInterface`? It would be a lot less confusing I think.

**Comment by drupol** [comment]
Hello,

I'm afraid but this won't happen anytime soon. I'm quite flexible, but this is a no-go.

I invite you to read this post: https://verraes.net/2013/09/sensible-interfaces/ from @mathiasverraes

Have a nice day.
