### ISSUE TITLE
Collection interface doesn't extend Countable

### ISSUE THREAD

**Issue by ktrzos** [loophp/collection#291]
Hey 👋

```php
use loophp\collection\Contract\Collection;

function func(Collection $collection): int {
	$collection->filter(...)->count();
}
```

PHPStan is telling me that:

> Call to an undefined method loophp\collection\Contract\Collection<int, object>::count()

I think the issue is with missing `Countable` interface on `Collection` interface.

**Comment by drupol** [comment]
Hi !

I'm aware of that. It was difficult for me to remove the `Countable` interface since this `Collection` library uses iterators and iterators are potentially infinite.

Therefore, I left the choice to the user.

If you play with the concrete `Collection` class, then, you can use `count()`:

```php
use loophp\collection\Collection; // Use the concrete object instead of using the interface.

function func(Collection $collection): int {
	$collection->filter(...)->count();
}
```

If you implement the `Collection` interface, then, it's up to the developer to implement or not the `Countable` interface.

Let me know if this is a solution that works for you.

**Comment by ktrzos** [comment]
Thanks! It works. Though a new problem appeared. I have this simple class:

```php
use loophp\collection\Collection;

final class MyClass
{
    /**
     * @var Collection<int, OtherClass>
     */
    private Collection $list;

    public function __construct()
    {
        $this->list = Collection::fromIterable([]);
    }

    public function handle(OtherClass $item): void
    {
        $this->list = $this->list->append($item);
    }

    /**
     * @param class-string<OtherClass> $class
     */
    public function isHandled(string $class): bool
    {
        return 0 < $this->list
            ->filter(static fn (OtherClass $item) => $item instanceof $class)
            ->count();
    }
}
```

And PHPStan is now informing about other issue:

> Property MyClass::$list (loophp\collection\Collection<int, OtherClass>) does not accept loophp\collection\Contract\Collection<int, OtherClass>.

So the class and the interface are mixed. Previously I've been using the interface. Would you be able to suggest something to resolve it?

**Comment by drupol** [comment]
Hey !

Let me rethink that in the next version, I promise, I'll ask @AlexandruGG as well.

As a workaround fix, you can declare the property as such:

```php
     * @var Collection<int, OtherClass>|CollectionInterface<int, OtherClass>
 `````

Let us know how it goes.

**Comment by AlexandruGG** [comment]
> 

Hey @ktrzos, thanks for raising this.

Looking at what your code is doing I have the following suggestions:

1. You might not need `count` in this case at all. You can write your function as such:

A) using [isEmpty](https://loophp-collection.readthedocs.io/en/latest/pages/api.html#isempty) -> this is also recommended in the [docs for count](https://loophp-collection.readthedocs.io/en/latest/pages/api.html#count) when checking if the collection is empty

```PHP
/**
 * @param class-string<OtherClass> $class
 */
public function isHandled(string $class): bool
{
    return $this->list
        ->filter(static fn (OtherClass $item) => $item instanceof $class)
        ->isEmpty();
}
```

B) using [match](https://loophp-collection.readthedocs.io/en/latest/pages/api.html#match)

```PHP
/**
 * @param class-string<OtherClass> $class
 */
public function isHandled(string $class): bool
{
    return !$this->list
        ->match(static fn (OtherClass $item) => $item instanceof $class);
}
```

2. I personally recommend always using the interface (`loophp\collection\Contract\Collection`) to avoid static analysis issues and complications like the one you referenced.

3. If you absolutely do need to use `count`, limit the usage of the Collection class type hint as much as possible. Something like this with your example:

```PHP
use loophp\collection\Collection;
use loophp\collection\Contract\Collection as CollectionInterface;

final class MyClass
{
    /**
     * @var CollectionInterface<int, OtherClass>
     */
    private CollectionInterface $list;

    public function __construct()
    {
        $this->list = Collection::fromIterable([]);
    }

    public function handle(OtherClass $item): void
    {
        $this->list = $this->list->append($item);
    }

    /**
     * @param class-string<OtherClass> $class
     */
    public function isHandled(string $class): bool
    {
        Assert::isInstanceOf($this->list, Collection::class);

        return 0 < $this->list
            ->filter(static fn (OtherClass $item) => $item instanceof $class)
            ->count();
    }
}
```

This should work with whichever assertion library, though I prefer [webmozarts/assert](https://github.com/webmozarts/assert). Lastly, if you don't want to use assertions you can use an `@var` annotation to achieve the same thing :).

**Comment by ktrzos** [comment]
@AlexandruGG @drupol 
Thank you very much for detailed suggestions, guys 💕. Love the `isEmpty()` and `has()` solutions. Changed on one of those and all is working now. Thank you once again! Closing the issue 🙂.

BTW. Have you been thinking about adding `isNotEmpty()` 🙂?

**Comment by drupol** [comment]
Why not? Are you willing to contribute?

**Comment by ktrzos** [comment]
I can try 😁.

**Comment by drupol** [comment]
Good idea ! You can count on us to assist during the process :)
