### ISSUE TITLE
Unexpected behavior of pair operation over empty collection

### ISSUE THREAD

**Issue by yesid-stf** [loophp/collection#326]
## Steps required to reproduce the problem

See following code example:

```php
Collection::fromIterable([])->pair()->all(false)
```

## Expected Result

It was expected that code would return empty array `[]`

## Actual Result

But it returns following garbage information:

```php
array:1 [
  "" => null
]
```

**Comment by drupol** [comment]
Hi !

Thanks for reporting the issue, nice catch!

I fixed it in #327 and added a test.
