### ISSUE TITLE
Code example in docs are unreadable

### ISSUE THREAD

**Issue by that-guy-iain** [loophp/collection#345]
## Steps required to reproduce the problem
Go to the docs site

## Expected Result

I can clearly read and set the code

## Actual Result

![image](https://github.com/user-attachments/assets/58495314-7d1c-43ca-a2b6-9227754e2aea)

I have to look very hard or select all the code.

**Comment by drupol** [comment]
Hi !

Thanks for the report. Someone already fixed this at https://github.com/loophp/collection/pull/311

Maybe you could provide a PR fixing this in here too?

In any case, if you're looking for that particular code example, you can find it in https://github.com/loophp/collection/blob/master/docs/pages/code/simple.php and the rest in https://github.com/loophp/collection/tree/master/docs/pages/code

**Comment by that-guy-iain** [comment]
Sorry, I'm really busy and working on my thing about 12 hours a day. If I had time I would but I really don't.

**Comment by drupol** [comment]
It's totally fine, I'll pick it up at some point when I'll have some time too.

**Comment by that-guy-iain** [comment]
I think you should probably increase the time limit on your bot if you're as busy. Seems silly to lose issues like this because everyone is too busy to fix it straight away and it's a low traffic repository like this.
