### ISSUE TITLE
Collection Contract & Countable

### ISSUE THREAD

**Issue by rela589n** [loophp/collection#348]
Currently `Countable` interface is only implemented in concrete `\loophp\collection\Collection` implementation.

Yet, in most cases we depend on the collection contract, and if we try to `count($collection)` we'll get the following phpstan error:

```
38     Parameter #1 $value of function count expects array|Countable, loophp\collection\Contract\Collection<int, string> given.  
         ✏️                  
```

IMO,  `Countable` should be implemented on `\loophp\collection\Contract\Collection`.

**Comment by rela589n** [comment]
BTW, are there any use-cases of `associate()` with two parameters (both `$callbackForKeys` and `$callbackForValues`) that could not be implemented with `associate()` + `$callbackForKeys` and just `map`?

**Comment by rela589n** [comment]
Hi, @drupol 

what do you think about this?

**Comment by drupol** [comment]
I don't think this is a good idea. This library handle stream, and counting a stream requires the whole stream to be available before counting it. Not making it countable is precisely what makes it lazy and I would like to keep it as such.
