### ISSUE TITLE
More specific Chunkable::chunk() return type

### ISSUE THREAD

**Issue by rela589n** [loophp/collection#350]
Currently `Chunkable` interface looks like this:

```php
/**
 * @template TKey
 * @template T
 */
interface Chunkable
{
    /**
     * Chunk a collection of items into chunks of items of a given size.
     *
     * @see https://loophp-collection.readthedocs.io/en/stable/pages/api.html#chunk
     *
     * @return Collection<int, list<T>>
     */
    public function chunk(int ...$sizes): Collection;
}
```

As you can see, this operation returns `Collection<int, list<T>>`, which is fair. 

Yet, since after applying `chunk()`, each produced chunk can will never be empty list.

Therefore, maybe it would make sense to specify `Collection<int, non-empty-list<T>>` as a return type, since this is more specific.

**Comment by drupol** [comment]
Hello,

Yes! Nice catch.

Please submit a PR to fix this and I'll merge it.

**Comment by rela589n** [comment]
Closing as completed
