### ISSUE TITLE
collection not working with php 8.0

### ISSUE THREAD

**Issue by MartkCz** [loophp/collection#56]
PHP 8.0 introduces new expression named match, which is BC break for classes and functions named same as keyword "match"

https://github.com/loophp/collection/blob/master/src/Operation/Match.php

**Comment by drupol** [comment]
Oh... This is unfortunate :(

I will rename it in v4, will work on it tonight.

Sorry for the inconveniences ...

**Comment by drupol** [comment]
I just released the version 3.3.5 that address this issue.

Could you please check? And close the ticket if it's ok?

Also, I haven't the chance to work with PHP 8 yet, looks like you do, how it's behaving in PHP 8? Is it ok? Do you see a difference with PHP 7 ?

**Comment by MartkCz** [comment]
I run php linter for all files and no syntax errors. Thank you!

**Comment by drupol** [comment]
Great, thanks!
