### ISSUE TITLE
apply() functionality

### ISSUE THREAD

**Issue by slackernrrd** [loophp/collection#62]
I'm not sure if this is a bug or if I just don't understand how this is supposed to work.

The documentation for Collection::apply() states:

> Execute a callback for each element of the collection without altering the collection item itself.
> 
> If the callback does not return true then it stops.

To me, this implies functionality similar to foreach. Returning `false` should stop the callback from executing for the items that follow.

In reality the apply() method executes the callback for every item regardless of the return value. However, if you supply several callbacks, returning `false` from one of them stops execution of the _following callbacks_, which is not the same.

After the following example, I would expect `$count === 2` but in reality `$count === 3`.

```php
$count = 0;

$fn = function($value) use (&$count) {
    $count++;
    if ($value === 'b') {
        return false;
    }

    return true;
}

Collection::fromIterable(['a', 'b', 'c'])
    ->apply($fn)
    ->all();
```

After running this code, with two callbacks (the same `$fn` from above), I would expect `$count === 2`, or possibly `$count === 4`, but in reality `$count === 5`:

```php
$count = 0;

Collection::fromIterable(['a', 'b', 'c'])
    ->apply($fn, $fn)
    ->all();
```

The callbacks will be called in this order:

'a': callback 1, callback 2
'b': callback 1,
'c': callback 1, callback 2

If this is the intended behaviour, is there another way to achieve foreach-like behaviour?

**Comment by drupol** [comment]
Hi @slackernrrd !

Thanks for opening the issue.

I will try to dedicate some time and tests your snippets, thanks for it, it's very appreciated.

What I can tell you already is that I'm not a big fan of the Apply operation, I don't like its implementation and I guess it needs to be revisited. 

Have a good evening.

**Comment by drupol** [comment]
After thinking about it a couple of minutes more, I think you're right.

We should never stop iterating, no matter what is the return of the callback.
However, we can stop applying the callbacks based on that return value.

I opened a PR (#63), could you please test it and let me know if it's better?

Thanks.

**Comment by slackernrrd** [comment]
Hi!

Thanks for looking into it so quickly @drupol. And thanks for a great library!

I tested your changes, and it works as expected for my use case! When using only one callback, the results are straightforward to understand.

When using multiple callbacks, however, the result is harder to understand. If the callbacks return false for different items, the end result (that is, which callback is applied to which values) is different depending on the order of the callbacks.

For instance, consider the following two callbacks:

```php
$fn1 = function($value) use (&$count) {
    if ($value === 'b') {
        return false;
    }

    return true;
}

$fn2 = function($value) use (&$count) {
    if ($value === 'c') {
        return false;
    }

    return true;
}
```

Then this code:

```php
Collection::fromIterable(['a', 'b', 'c'])
    ->apply($fn1, $fn2)
    ->all();
```

...will result in the following calls:

'a': $fn1, $fn2
'b': $fn1, $fn2
'c': $fn1, $fn2

But having the callbacks in the reverse order (`->apply($fn2, $fn1)`) will result in the following calls:

'a': $fn2, $fn1
'b': $fn2, $fn1
'c': -

Maybe that is the desired result.

In my mind, I would expect the following calls, regardless of the order that the callbacks were provided:

'a': $fn1, $fn2
'b': $fn1, $fn2
'c': $fn2

**Comment by drupol** [comment]
Dear @slackernrrd ,

I updated the tests and fix the behavior. What you described was making sense. Have a look at them, and let me know what you think.

However, the only thing that is not possible to implement is the order of execution of the callbacks.
They will be executed in the natural order. Thus, it's not possible to expect the same result regardless of the order.
Unless I misunderstood your point, I got no clue on how to implement it.

Have a good evening.

**Comment by slackernrrd** [comment]
Hi @drupol ,

I've looked at the tests and they look good to me. Even though the test result would differ if the callbacks were called in a different order, with the last update in behaviour there _is_ a simple logic (as far as I can tell) - each callback runs until it returns false (and that's true regardless of the order).

Perhaps the docs could be updated with regard to providing multiple callbacks?

**Comment by drupol** [comment]
> Hi @drupol ,
> 
> I've looked at the tests and they look good to me. Even though the test result would differ if the callbacks were called in a different order, with the last update in behaviour there _is_ a simple logic (as far as I can tell) - each callback runs until it returns false (and that's true regardless of the order).

Great new :-)

> Perhaps the docs could be updated with regard to providing multiple callbacks?

Yes, I added a checkbox in the PR, I will fix it tonight.

I'll ping you in the PR when it's done so you can quickly review?

Thanks!

**Comment by drupol** [comment]
Great, thanks for the report again and for the review! Feel free to contact me again in case of issue.
