### ISSUE TITLE
why does map expect return type to be a subtype

### ISSUE THREAD

**Issue by aszenz** [loophp/collection#71]
```php
class Quantity {
  public float $value;
  public string $unitCode;
}
 // psalm error here
$qtys = $value = Collection::fromIterable($qtys)->map(fn (Quantity $qty): float => $qty->value);
```
The canonical type definition of map 
`map : (T -> V) -> List T -> List V`, 
where T and V are generic type variables, as far as i know there is no requirement of V being a sub type of T in other languages

**Comment by drupol** [comment]
Hello,

Indeed, we cannot force **V** to be a subtype of **T** in PHP.

There is no way to check that the callback you use returns the proper type - unless doing very weird stuff with the Reflection API and I don't want to go in there, it might have a huge impact on perf.

**Comment by aszenz** [comment]
> Hello,
> 
> Indeed, we cannot force **V** to be a subtype of **T** in PHP.
> 
> There is no way to check that the callback you use returns the proper type - unless doing very weird stuff with the Reflection API and I don't want to go in there, it might have a huge impact on perf.
The above code doesn't pass psalm, but I think it's perfectly fine for V to not be a subtype of T.

Here's how I think the annotation should be

```php
     * @param callable ...$callbacks
     * @psalm-param callable(T, TKey, Iterator<TKey, T>): **V** ...$callbacks
     *
     * @psalm-return \loophp\collection\Collection<TKey, **V**>
     *
```

**Comment by drupol** [comment]
oooh that.

Yes, PSalm annotations could be improved, I tried to do my best, but I guess there are many improvements left to be done.

Do you want to submit a PR ?
