### ISSUE TITLE
FlatMap + Eager Usage

### ISSUE THREAD

**Issue by AlexandruGG** [loophp/collection#80]
Hello,

Firstly, thank you for creating this library! I was also looking into writing a Collections library to replace the Doctrine Collections I typically use in Symfony projects because I couldn't find any good replacement with sufficient functionality, strict typing, proper code analysis and code quality checks etc. And just today I found your library, which looks awesome! 😄

I have two main questions:
1. I can't see any `flatMap` operation being available (also called `bind` in other languages). I know one can do `map`+ `flatten` but I think it's a common enough operation that having it would be nice. What do you think? I'd be happy to contribute!

2. If I want to apply a collection operation _eagerly_ rather than _lazily_ in a certain instance, but I still want to keep the collection rather than transform to an array, what's the best way to do it? Is it to call `apply()`? Let's say I'm calling `map()` with a function that throws an exception, and then returning the collection. I want the exception to be thrown at that level rather than at a level higher, where the collection is used. Due to the lazy nature, simply calling `map` will not cause the exception to be thrown.

I hope I've explained this well enough but let me know if I should clarify or provide an example! Thanks!

**Comment by drupol** [comment]
Hi!

Thanks for reaching out and glad it helps :) That's the idea!

1. Indeed, the `flatMap` operation is not available and could be added quickly. See the [README](https://github.com/loophp/collection#features), there is an implementation of a `flatMap` as example.

2. This is a good question. I think this is currently not possible. This collection library is completely lazy and will iterate only when it is being used in a loop (`for, foreach, while`, etc etc) or on some particular operations like `Collection::all()` which convert the collection into a bare array (_that operation is a degenerative operation, be careful, you may lose data while doing that_). The `apply` is not a solution either, it won't help you either.

For both of your questions, you're more than welcome to contribute by sending pull-request(s), we can than discuss the technical details in there.

Hope it helps!

Cheers.

**Comment by AlexandruGG** [comment]
Hey @drupol,

Thank you for the lightning-fast reply!

On the second point regarding eagerness, I just want to provide a small example to explain my rationale and hear your opinion about the usage:

```PHP
class PhoneFactory
{
    /**
     * @param Collection<int, string|null> $rawNumbers
     *
     * @throws PhoneNumberException
     *
     * @return Collection<int, PhoneNumber>
     */
    public function createNumbers(Collection $rawNumbers): Collection
    {
        return $rawNumbers->map(fn(?string $rawNumber): PhoneNumber => $this->create($rawNumber));
    }

    private function create(?string $rawNumber)
    {
        if ($rawNumber === null) {
            throw new PhoneNumberException('Phone number cannot be null.');
        }

        return PhoneNumber::parse($rawNumber);
    }
}
```

In a simplified example like this, all that's happening is applying a transformation which can fail - the method can throw `PhoneNumberException`. If I want to fully cover this method with unit tests and assert that an exception is thrown, in this current format I cannot do so using the library because the actual transformation isn't applied in this method due to the collection's lazy nature.

So in order to actually test the exception path, correct me if I'm wrong, but I would have to do something like this if I want to return the collection rather than transform to an array:

```PHP
return Collection::fromIterable($rawNumbers->map(...)->all());
```

For instances like this perhaps a method like `eager()` would be helpful?
```PHP
return $rawNumbers->map(...)->eager();
```

I imagine the behaviour would be the same or very similar to the previous "workaround".

I'm curious to hear your view on this and how you would approach this. Sorry if this isn't the best place for this 😅.

Cheers!

**Comment by drupol** [comment]
Hi,

I definitely see and understand what you're trying to do.

After a couple of hours of thinking about it, here's my point of view:

1. This is not the purpose of the library. The purpose of this library is to handle data in a lazy way, and exceptions needs to be handled in a different way. I do not pretend to have the solution yet, but all I know is that we have to change our habits when working with lazyness.
2. I think you should clean your data before using the library. In your case, you could use `Collection::compact()` or `Collection::filter()` to clean the dataset before applying the `Collection::map()`.  
3. What's you're trying to achieve is already possible, you made it right in your example. Even if this is not how I would have done, it will work as long as you have `keys` of type `int|string`. I quickly drafted a PR, see #82 Just for my information, could you please test it?

WDYT?

**Comment by AlexandruGG** [comment]
Hi again,

Thank you for creating the PR so quickly 😄 . I was going to do that if you agreed with it. I tested it and it behaves as expected for my use case.

I agree with your point about cleaning the data, the example provided is just a simplified version of what I wanted to convey. My main point was around the fact that in certain instances exceptions will be thrown and you want to be able to test that code path.

A case could be made for using exceptions more sparingly (I'm not particularly fond of them), and instead returning a `Result<Collection, Error>` from these kinds of methods. Then, the calling method could stop the operation based on that, rather than relying on the exception being thrown to stop the operation. Realistically however, in PHPland this is not too common yet.

I think having this capability would allow more flexibility in usage, but I also understand if you think this usage goes against the principle of the library.

**Comment by drupol** [comment]
Dear @AlexandruGG ,

I made a new PR #83:

I renamed it to `Squash`
I added a parameter: `$throwOnException`

What do you think?

I think it's clean enough as it is to be introduced in the library, despite the fact that this is a huge performance hit.
As long as the documentation will reflect this, I'm ok.

Thanks!

**Comment by AlexandruGG** [comment]
Thank you @drupol, the name sounds good to me and the behaviour is still as expected if the default value for the parameter is used. I left a comment on the PR to better understand what you were thinking regarding the exception handling.

**Comment by drupol** [comment]
PR #83  is now ready for your last review :)

Have a good sunday!
